### ISSUE TITLE
Skipped tests cause agent to crash

### ISSUE THREAD

**Issue by justinanastos** [zebrunner/javascript-agent-cypress#15]
The cypress reporter throw errors whenever tracking skipped tests:

```
new worker process was created in detached mode
ipc server was started with alias zbr-23249
client was connected to zbr reporter's ipc server with alias 'zbr-23249'
config was emitted
ReferenceError: testItemStatuses is not defined
    at parseTestInfo (/Users/xxxx/proj/app/marketing/node_modules/@zebrunner/javascript-agent-cypress/lib/object-transformer.js:24:51)
    at /Users/xxxx/proj/app/marketing/node_modules/@zebrunner/javascript-agent-cypress/lib/cypress-zebrunner.js:88:19
    at runMicrotasks (<anonymous>:null:null)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

ReferenceError: testItemStatuses is not defined
    at parseTestInfo (/Users/xxxx/proj/app/marketing/node_modules/@zebrunner/javascript-agent-cypress/lib/object-transformer.js:24:51)
    at /Users/xxxx/proj/app/marketing/node_modules/@zebrunner/javascript-agent-cypress/lib/cypress-zebrunner.js:88:19
    at runMicrotasks (<anonymous>:null:null)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

----- Cypress running is done -----
```

This is presumably because of the reference to `testItemStatuses` that doesn't exist on https://github.com/zebrunner/javascript-agent-cypress/blob/master/lib/object-transformer.js#L21. These tests then appear to be "In Progress" forever.

**Comment by MitskevichVS** [comment]
Hey @justinanastos, thanks for opening an issue
Fix has been released in ver. 1.0.32
If you are still experiencing this issue after upgrading to 1.0.32, please open a new issue.
